version: "3.8"

services:
  llm-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-kobart-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./patch:/app/patch
      - ./main.py:/app/main.py
      - ./requirements.txt:/app/requirements.txt
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - kafka-net

networks:
  kafka-net:
    external:
      name: kafka_kafka-net

